### ISSUE TITLE
tracking: virtual memory and heap allocator

### ISSUE THREAD

**Issue by georglauterbach** [georglauterbach/uncore#21]
The kernel needs a memory allocator that can perform simple allocations. With such an allocator, we can use `alloc::` to use `alloc::sync::Arc` for proper multi-threading safe contexts. This requires support from **virtual memory**.

Tracking / missing features / bugs:

- [x] The default heap allocator does not yet seem to properly work (the fallback allocator has to be used sometimes)
- [x] The code needs cleanup and proper comments
- [x] The kernel needs architecture agnostic memory management types
- [ ] Take care of deallocation off pages as well
- [x] Proper address alignment
- [x] Add `derive` to types
- [x] Add proper implementations for standard operators on addresses
- [ ] Better error handling

**Comment by georglauterbach** [comment]
Tracking / missing features / bugs:

- [ ] The default heap allocator does not yet seem to properly work (the fallback allocator has to be used sometimes)
- [ ] The code needs cleanup and proper comments
- [ ] The kernel needs architecture agnostic memory management types

**Comment by georglauterbach** [comment]
Going through old issues that are open for a long time; I will close this as I will not be able to work on it soon and I would like my issue tracker to be clean :)
