### ISSUE TITLE
UEFI bootloader integration: tracking

### ISSUE THREAD

**Issue by georglauterbach** [georglauterbach/uncore#26]
Because we changed (back) to using RustOSDev's bootloader crate, but this time with UEFI, there are some open TODOs before we head back to writing memory code:

- [x] adjust documentation
- [x] fix `stack_overflow` integration test
- [x] miscellaneous small fixes before PR gets merged
- [x] fix `panic` with tests
- [x] add option to `never_return()` to exit QEMU at the same time
