### ISSUE TITLE
tracking: adoption of RISC-V

### ISSUE THREAD

**Issue by georglauterbach** [georglauterbach/uncore#53]
This is a tracking issue.

### Tasks

- [x] resolve current TODOs:
  - [x] `/// TODO`
  - [x] `//! TODO`
  - [x] `TODO`
- [x] update GitHub issue templates
- [x] lint EC with GitHub actions
- [x] lint yamllint with GitHub actions
- [ ] update the documentation
  - [x] <https://github.com/qemu/qemu/blob/v8.1.2/hw/riscv/virt.c> 
  - [x] <https://blog.henrygressmann.de/rust-os/2-shell/>
  - [x] <https://mth.st/blog/riscv-qemu/>
  - [x] https://github.com/riscv-non-isa/riscv-asm-manual/blob/master/riscv-asm.md
  - [x] https://web.eecs.utk.edu/~smarz1/courses/ece356/notes/assembly/
  - [x] update doc contents
- [x] get integration tests to work
- [x] run tests with timeout
- [x] add support for running on multiple HARTs
- [x] add support for dynamically managed memory on the heap
